### ISSUE TITLE
SyncSerial vs SerialSync?

### ISSUE THREAD

**Issue by valuta1995** [metafetish/liblovense-py#6]
It appears that examples/get_device_info relies on importing "LovenseSyncSerial" from lovense.comm; however, comm.py only has "LovesenseSerialSync"

**Comment by qdot** [comment]
Whoops. I'll try to get that fixed, thanks!

**Comment by qdot** [comment]
Project shutting down as we now support Lovense toys in https://github.com/buttplugio/buttplug, closing bug as WONTFIX
